// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkRequestTracker.Infrastructure.Persistence;

#nullable disable

namespace WorkRequestTracker.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260504042529_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("WorkRequestTracker.Domain.Entities.Note", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkRequestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkRequestId")
                        .HasDatabaseName("IX_Notes_WorkRequestId");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = "b1b2c3d4-0001-0000-0000-000000000001",
                            Content = "Initial mockups approved by the client. Moving to development phase.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkRequestId = "a1b2c3d4-0001-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = "b1b2c3d4-0002-0000-0000-000000000002",
                            Content = "Header and hero section completed. Footer still in progress.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkRequestId = "a1b2c3d4-0001-0000-0000-000000000001"
                        },
                        new
                        {
                            Id = "b1b2c3d4-0003-0000-0000-000000000003",
                            Content = "Confirmed the timeout is on the payment provider's side. Awaiting their API fix.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkRequestId = "a1b2c3d4-0002-0000-0000-000000000002"
                        },
                        new
                        {
                            Id = "b1b2c3d4-0004-0000-0000-000000000004",
                            Content = "Provider says fix will be deployed next week. Keeping status as Blocked.",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            WorkRequestId = "a1b2c3d4-0002-0000-0000-000000000002"
                        });
                });

            modelBuilder.Entity("WorkRequestTracker.Domain.Entities.WorkRequest", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_WorkRequests_Status");

                    b.HasIndex("Title")
                        .HasDatabaseName("IX_WorkRequests_Title");

                    b.ToTable("WorkRequests");

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-0001-0000-0000-000000000001",
                            ClientName = "Acme Corp",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Complete overhaul of the main landing page with new branding guidelines and responsive layout.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 2,
                            Status = 1,
                            Title = "Redesign Landing Page",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a1b2c3d4-0002-0000-0000-000000000002",
                            ClientName = "GlobalTech Solutions",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Payment processing times out after 30 seconds on high-traffic days. Investigate and fix.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 2,
                            Status = 2,
                            Title = "Fix Payment Gateway Timeout",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a1b2c3d4-0003-0000-0000-000000000003",
                            ClientName = "Acme Corp",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Users need the ability to export their order history to CSV format from the dashboard.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            Status = 0,
                            Title = "Add Export to CSV Feature",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a1b2c3d4-0004-0000-0000-000000000004",
                            ClientName = "Northwind Traders",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Legal team provided updated privacy policy text. Replace existing content and update footer links.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 0,
                            Status = 3,
                            Title = "Update Privacy Policy Page",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = "a1b2c3d4-0005-0000-0000-000000000005",
                            ClientName = "Summit Financial",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Implement push notification support for iOS and Android. Include transaction alerts and marketing opt-in.",
                            DueDate = new DateTimeOffset(new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Priority = 1,
                            Status = 0,
                            Title = "Mobile App Push Notifications",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("WorkRequestTracker.Domain.Entities.Note", b =>
                {
                    b.HasOne("WorkRequestTracker.Domain.Entities.WorkRequest", "WorkRequest")
                        .WithMany("Notes")
                        .HasForeignKey("WorkRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkRequest");
                });

            modelBuilder.Entity("WorkRequestTracker.Domain.Entities.WorkRequest", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
